all :
	g++ Enregistrement.cpp Horodatage.cpp Lampadaire.cpp Ampoule.cpp Galerie.cpp GPS.cpp Geolocalisation.cpp BDD.cpp Collecteur.cpp listerLampadairesProches.cpp -o lampProches.cgi -std=c++11 -lsqlite3 -lcgicc
